### ISSUE TITLE
Won't work on Windows other than Japanese locale

### ISSUE THREAD

**Issue by UlyssesWu** [yamachu/LibOpenJTalk#1]
Hi,

I'm using `SharpOpenJTalk 1.1.4`, but it doesn't actually work because my system is not in Japanese locale. The error is:

`WARNING: JPCommonLabel_make() in jcomon_label.c: No phoneme.`

So I guess the `openjtalk.dll` can only be used in Japanese locale. I tried the dlls both from `SharpOpenJTalk` nuget package and this repo's release page (they are the same thing actually) with no luck. 
(And you seems haven't export `Open_JTalk_synthesis_buffer` so no one can call `instance.SynthesisBuffer` just like your sample)

Then I tried to compile `LibOpenJTalk` (without changing makefiles). Of course there are a lot of warnings like this:

`warning C4566: character represented by universal-character-name '\uFF8F' cannot be represented in the current code page`

It seems to work but the synthesis result is uncompleted. The result of "おはようございます" sounds like "お...うございます". I believe it's also caused by the locale issue.
[wav.zip](https://github.com/yamachu/LibOpenJTalk/files/1765878/wav.zip)

I also tried `CHARSET_UTF_8` and `/utf-8`. There are no warnings when compiling, but the compiled dll won't work...

However, https://github.com/rosmarinus/jtalkdll as a contrast, can run on my system correctly. It seems to be compiled with Cygwin / MSYS2 / MinGW-w64 / gcc. (I definitely don't want to install them for compiling...)

**Comment by UlyssesWu** [comment]
By the way, I'm interested in the WORLD synthesis, but there are no model exists. Do you have a htsvoice with WORLD features (I guess it should be MGC,LF0,BAP) for test?

**Comment by yamachu** [comment]
Thank you for reporting.

I hadn't tested in windows yet...

> (And you seems haven't export Open_JTalk_synthesis_buffer so no one can call instance.SynthesisBuffer just like your sample)

I fixed in this commit (https://github.com/yamachu/LibOpenJTalk/commit/81c9f55e8c39f10959722a355aa1934d3e63ebc0)

> not in Japanese locale

See ref: http://ufcpp.net/blog/2016/12/tipsstringmarshal/

This page shows that `CharSet.Ansi` depends on machine locale.
So I'm working for using Unicode on Marshaling.  ([SharpOpenJTalk]( https://github.com/yamachu/SharpOpenJTalk/blob/master/library/src/Native/CoreDefinitions.cs))

> Do you have a htsvoice with WORLD features (I guess it should be MGC,LF0,BAP) for test?

I'm using this model for my research and I can not provide it now.

**Comment by yamachu** [comment]
I upload [new library](https://github.com/yamachu/SharpOpenJTalk/releases/tag/v_1.1.5) using Unicode.
This version might work...
Please try to use it.

**Comment by UlyssesWu** [comment]
Yes, it works. Thank you!
But when compiling `LibOpenJTalk`, the `utf8.h` is missing. Maybe it's better to add those files in this git repo, or use submodule?

**Comment by yamachu** [comment]
I made a mistake.
Add submodules in https://github.com/yamachu/LibOpenJTalk/commit/8f58102bd59288eeaa80b4745315cc65f8f6cd6a
Thank you for your advice!
